### ISSUE TITLE
Compatibility with Bazel 0.29.*

### ISSUE THREAD

**Issue by thundergolfer** [tubular/rules_pygen#6]
On account of [this recent change to `bazel`](https://github.com/bazelbuild/bazel/commit/1df6d77a399ba520c2991edd1fbec8e050629ed9#diff-80ce310d0ee40a6b80c72ed698fa778d) `rules_pygen` produces the following problem on `0.29.1`: 

```
ERROR: /private/var/tmp/_bazel_jonathonbelotti/1d31e26348def3cbe892454dd398945f/external/pypi__click_7_0/BUILD.bazel:3:1: name 'native' is not defined
ERROR: /private/var/tmp/_bazel_jonathonbelotti/1d31e26348def3cbe892454dd398945f/external/pypi__click_7_0/BUILD.bazel:3:1: name 'native' is not defined
```

**Comment by c4urself** [comment]
Thanks, is there a backwards-compatible fix we could use?

**Comment by bkad** [comment]
fixed in https://github.com/tubular/rules_pygen/commit/6bfce94e4aaebdc6fda73472fc71c3ac6bdc891e
